# Generated by Django 5.0.4 on 2024-04-07 07:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0003_conversation_user_course_user_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="message",
            name="is_human",
            field=models.BooleanField(default=True, null=True),
        ),
        migrations.AlterField(
            model_name="message",
            name="text",
            field=models.CharField(max_length=50000),
        ),
    ]
