# Generated by Django 5.0.4 on 2024-04-07 14:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0004_message_is_human_alter_message_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="conversation",
            name="files_in_index",
            field=models.ManyToManyField(
                related_name="in_conversation", to="chat.coursefile"
            ),
        ),
    ]
