# Generated by Django 5.0.4 on 2024-04-10 00:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0006_remove_conversation_files_in_index_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="coursefile",
            name="local_file",
            field=models.FileField(blank=True, null=True, upload_to="uploaded_files/"),
        ),
    ]
